### ISSUE TITLE
YAML domain knowledge file not working properly

### ISSUE THREAD

**Issue by matbord** [salesforce/PyRCA#60]
Hi, I am using the example code to create a DAG with the help of the YAML file
```
from pyrca.graphs.causal.pc import PC
model = PC(PC.config_class(domain_knowledge_file="file_path"))
graph_df = model.train(df)
```
the yaml file is he following

```
causal-graph:
  root-nodes: ["KPI"]
  leaf-nodes: []
  forbids:
  requires: 
    - ["connection", "KPI"]
    - ["inter", "KPI"]
    - ["early", "KPI"]
    - ["late", "KPI"]
    - ["wrong_cell", "KPI"]
    - ["cause", "KPI"]
    - ["unnecessary", "KPI"]
    - ["intra_cause", "KPI"]
```

but the resulted graph is missing 2 required connections, more specifically ["connection", "KPI"] and ["wrong_cell", "KPI"]. Why is this happening?
